### ISSUE TITLE
Document the Heap Ordering

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/morpho-data-structures#109]
Document the max size, how in effect only half of it is expected to be in the heap part of the data-structure. Explain the size, and how it tries to solve the issue of having all the liquidity in the same path

**Comment by MathisGD** [comment]
Can be batched with #19

**Comment by MerlinEgalite** [comment]
@Tristan22400 are you in it?

**Comment by Tristan22400** [comment]
> @Tristan22400 are you in it?

Yes the PR is ready for review
