### ISSUE TITLE
Conform to Morpho's style

### ISSUE THREAD

**Issue by MerlinEgalite** [morpho-org/morpho-data-structures#125]
Update NATSPECs + naming to Morpho coding style

**Comment by makcandrov** [comment]
Maybe we can merge some other enhancements inside this PR, namely
- Replace all the old import syntax with the new one (as discussed in #122)
- Use an underscore before the private functions in libraries (as highlighted by @QGarchery [here](https://github.com/morpho-dao/morpho-data-structures/pull/117#discussion_r1180060441)

**Comment by Tristan22400** [comment]
yes I agree, I will cover this in my PR.

**Comment by pakim249CAL** [comment]
Another change to consider is to conform to naming parameters without an underscore, as underscores should be reserved for internal function and variable names.
